### ISSUE TITLE
Question about deriving Eq.(17)

### ISSUE THREAD

**Issue by ThatDanielLiu** [danielzuegner/nettack#13]
I've derived Eq.(17) by myself but found that in the PROOF the A hat squared is not equals to the right hand side. In the definition of A, there's no tilde in a, but in A hat squared the tilde exists. This puzzled me. So how to derive Eq.(17)?

**Comment by danielzuegner** [comment]
Hi,

Thanks for your interest in our work. I'm not sure I understand the question, so I'll just give the answer a shot. Feel free to ask a follow-up question if anything remains unclear.

It seems that you're confused about `A`, `A_tilde`, and `A_hat` in the proof of Eq. (17). Specifically, the confusion seems to be about the first full-row equation in the proof `[A_hat_square]_{uv} = …`. The difference between `A_tilde` and `A` is subtle. As specified right below Eq. (1), `A_tilde` is the adjacency matrix with added self-loops (via adding the identity matrix). `A_hat`, on the other hand, is the degree-normalized version of `A_tilde` (see below Eq. (2)). 

In the proof we use at several places the fact that diagonal elements `A_{uu}=0` as we consider graphs without self-loops, while `A_tilde_{uu}=1` because we added the self-loops.

**Comment by ThatDanielLiu** [comment]
> 
Oh thanks for the detailed explanation, I totally get it.
