### ISSUE TITLE
Will the default execution of the code exactly reproduce the example image?

### ISSUE THREAD

**Issue by suyeecav** [danielzuegner/nettack#9]
If we strictly follow the setup in the code, will it produce exact same output as shown in the example image?  

I tried to run your demo code without any modification (but converted it to python file for convenience in running). However, the attack is not very effective and the correct class is shown to be class 1 instead of class 5 shown in the example output (node id is 0 and seed is 15). Since I did not modify anything, I am trying to figure out the possible reason.

**Comment by danielzuegner** [comment]
Hi. I've just noticed that by default the demo notebook has `perturb_structure=False`, which is not the setting we used in the paper and for generating the example figure. I've changed that now -- can you try again with the updated settings? You will most likely not get the **exact** same results since we are not setting the tensorflow seed, but it should be pretty close. Let me know if it works so that I can close this issue then.

Thanks!

**Comment by suyeecav** [comment]
> Hi. I've just noticed that by default the demo notebook has `perturb_structure=False`, which is not the setting we used in the paper and for generating the example figure. I've changed that now -- can you try again with the updated settings? You will most likely not get the **exact** same results since we are not setting the tensorflow seed, but it should be pretty close. Let me know if it works so that I can close this issue then.
> 
> Thanks!

Thanks for the response. It works perfectly now, at least misclassification can be easily reached.
